name: CI/CD Simulation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps (for a quick smoke test)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test (import + dry run)
        run: |
          python - << 'PY'
          import pandas, matplotlib
          print("Smoke OK")
          PY

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest

      # Simulated deployment: run container in CI and emit artifacts
      - name: Run container (simulate deployment)
        run: |
          mkdir -p outputs
          mkdir -p data
          # if you keep All_Diets.csv out of repo, this step will just run with empty data dir (that's OK for demo)
          docker run --rm \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/outputs:/app/outputs \
            ${{ secrets.DOCKERHUB_USERNAME }}/diet-analysis:latest
          ls -alh outputs || true

      - name: Upload outputs as artifact (proof)
        uses: actions/upload-artifact@v4
        with:
          name: task1-outputs
          path: outputs
          if-no-files-found: warn
